### ISSUE TITLE
LFX 2023 Term 3: Sep-Nov administration umbrella issue

### ISSUE THREAD

**Issue by nate-double-u** [cncf/mentoring#1053]
## Start of term

- [x] Call for proposals announcement (about 1 month ahead of proposal due date)
  - [x] TOC mail list
  - [x] Maintainers newsletter
  - [x] Discussion boards
  - [x] Linkedin/Twitter/Mastodon
  - [x] CNCF Slack (#mentoring & #tag-contributor-strategy)
- [x] Followup announcement about 1 week ahead of deadline

## Proposals in

- [x] Load proposals into LFX platform 
  - https://github.com/cncf/mentoring/pull/1054
  - https://github.com/cncf/mentoring/pull/1059
  - https://github.com/cncf/mentoring/pull/1060
  - https://github.com/cncf/mentoring/pull/1064
  - https://github.com/cncf/mentoring/pull/1065
  - https://github.com/cncf/mentoring/pull/1068
  - [x] Create Sep-Nov Project, Mentor, & Mentee list (gsheet)
- [x] Open projects for application (LFX platform)
- [x] Mentee applications open announcement 
  - [x] Reach out to CNCF Socials team
  - [x] Discussion boards https://github.com/cncf/mentoring/discussions/1066
  - [x] Linkedin/Twitter/Mastodon
    - https://www.linkedin.com/feed/update/urn:li:activity:7092491748383305728/
    - https://twitter.com/CloudNativeFdn/status/1686726065115287552
    - https://fosstodon.org/@contribstrat/110820517598279883
  - [x] CNCF Slack (#mentoring & #tag-contributor-strategy)
- [ ] ~Followup email to mentors that mentees are applying (a week before deadline -- they can start looking at their candidates)~ Missed — @nate-double-u 
- [x] Application deadline
  - [x] Close projects for applications (LFX platform)
  - [x] email mentors that they should be making selections
- [x] Create mentor email list
- [x] Send welcome/get started email to mentors

## Application review/admission decisions
- [x] email mentors to make selections (share google form)
- [x] CNCF Selection admin (in LFX platform, accept project's selected mentee, decline others)
  - [x] first pass complete (most projects have been processed)
  - [x] remainder of approvals 
- [ ] ~Create mentee email list~ Most emails to mentees are better done via mail-merge. Discussion and announcemetns can be done on the [discussion boards](https://github.com/cncf/mentoring/discussions).

## Midterm

- [x] Midterm evaluation (Mentors)
  - [x] Create google form
  - [x] Send evaluation form to mentors (about 1-2 weeks before due)
- [x] Send out evaluation results & stipend instructions ([Mail merge](https://developers.google.com/apps-script/samples/automations/mail-merge))
- [x] Approve stipends

## End of term

- [x] End of term evaluation (Mentors)
  - [x] Create google form
  - [x] Send evaluation form to mentors (about 1-2 weeks before due) (Sent Nov 14, 2023)
- [x] Send out evaluation results & stipend instructions ([Mail merge](https://developers.google.com/apps-script/samples/automations/mail-merge))
- [x] Approve stipends
- [x] Mentee feedback - (open form on evaluation due date, feedback/blog posts due on last day of term)
  - [x] Send feedback form to mentees (include deadline, last day of term)
  - [x] Send feedback reminder if needed
- [x] Reach out to CNCF blog team to write end of term blog post (blog@cncf.io)
  - [x] Share end of term blog post: https://www.cncf.io/blog/2023/12/14/lfx-programs-cncf-mentees-have-successfully-finished-term-3/
	- [x] Linkedin/Twitter/Mastodon https://www.linkedin.com/posts/cloud-native-computing-foundation_mentorship-lfx-activity-7141121947811098624-GU0P?utm_source=share&utm_medium=member_desktop, 
- [x] Update statistics
  - [x] [CNCF Mentoring Stats Overview (ongoing summary)](https://docs.google.com/spreadsheets/d/13xybjxyWOHcfNn3Mmpd6zbq61gLp5Kprdsda-nJ50lM/edit?usp=sharing)
  - [x] [cncf/mentoring Program Statistics](https://github.com/cncf/mentoring#program-statistics) https://github.com/cncf/mentoring/pull/1104
  - [x] [cncf/mentoring programs](https://github.com/cncf/mentoring/tree/main/programs) https://github.com/cncf/mentoring/pull/1104

## Post term

- [x] Send thank you email to all of the mentors
- [ ] Plan / setup next term (terms should be planned a year in advance - at the end of this term, plan next  year's)
  - [ ] 2024 Term 3 https://github.com/cncf/mentoring/issues/1107

**Comment by nate-double-u** [comment]
Closing as complete, planning is all that remains, and I've opened an issue for that.
