### ISSUE TITLE
[umbrella] LFX 2024 Term 1: Mar-May administration

### ISSUE THREAD

**Issue by nate-double-u** [cncf/mentoring#1077]
## Before term
- [x] Plan term https://github.com/cncf/mentoring/issues/1070

## Start of term

- [x] Call for proposals announcement (about 1 month ahead of proposal due date)
  - [x] TOC mail list - NW scheduled an email for Jan 8, 2024 @ 9:00AM PST
  - [x] Maintainers newsletter
  - [x] Discussion boards
  - [x] Linkedin/Twitter/Mastodon
  - [x] CNCF Slack (#mentoring & #tag-contributor-strategy)
- [x] Followup announcement about 1 week ahead of deadline

## Proposals in

- [x] Load proposals into LFX platform 
  - [x] Create Mar-May Project, Mentor, & Mentee list (gsheet)
- [X] Open projects for application (LFX platform)
- [x] Mentee applications open announcement 
  - [x] Reach out to CNCF Socials team
  - [x] Discussion boards - https://github.com/cncf/mentoring/discussions/1150
  - [x] Linkedin/Twitter/Mastodon/others? Linkedin is most important based on previous traffic.
    -  https://www.linkedin.com/posts/cloud-native-computing-foundation_the-lfx-mentorship-2024-term-01-march-may-activity-7158234077291008000-h8Tu?utm_source=share&utm_medium=member_desktop
    - https://www.linkedin.com/posts/aliok_lfx-mentorship-mentee-applications-for-24-activity-7157991072437055488-fDLD?utm_source=share&utm_medium=member_desktop
    - https://twitter.com/CloudNativeFdn/status/1752468386385215919
    - https://mstdn.ca/@natew/111847437454334037
  - [x] CNCF Slack (#mentoring) - https://cloud-native.slack.com/archives/CGPK98JNQ/p1706570156038399
- [x] Followup email to mentors that mentees are applying (a week before deadline -- they can start looking at their candidates)
- [x] Application deadline
  - [x] Close projects for applications (LFX platform)
  - [x] email mentors that they should be making selections
- [x] Create mentor email list

## Application review/admission decisions
- [x] email mentors to make selections (share google form)
- [x] CNCF Selection admin (in LFX platform, accept project's selected mentee, decline others)
  - [x] first pass complete (most projects have been processed)
  - [x] remainder of approvals 
- [x] Create mentee email list

## Midterm

- [x] Midterm evaluation
  - [x] Create google form
  - [x] Send evaluation form to mentors (about 1-2 weeks before due) - Scheduled email for Apr 2, 2024 @ 9:00 AM Pacific time
- [x] Send out evaluation results & stipend instructions ([Mail merge](https://developers.google.com/apps-script/samples/automations/mail-merge))
- [ ] Approve stipends

## End of term

- [x] End of term evaluation (Mentors)
  - [x] Create google form
  - [x] Send evaluation form to mentors (about 1-2 weeks before due)
- [x] Send out evaluation results & stipend instructions ([Mail merge](https://developers.google.com/apps-script/samples/automations/mail-merge))
- [x] Approve stipends
- [ ] Mentee feedback - (open form on evaluation due date, feedback/blog posts due on last day of term)
  - [x] Send feedback form to mentees (include deadline, last day of term)
  - [x] Send feedback reminder if needed
- [x] Reach out to CNCF blog team to write end of term blog post (blog@cncf.io)
  - [x] Share end of term blog post
	- [x] Linkedin/Twitter/Mastodon
- [x] Update statistics
  - [x] [CNCF Mentoring Stats Overview (ongoing summary)](https://docs.google.com/spreadsheets/d/13xybjxyWOHcfNn3Mmpd6zbq61gLp5Kprdsda-nJ50lM/edit?usp=sharing)
  - [ ] [cncf/mentoring Program Statistics](https://github.com/cncf/mentoring#program-statistics)
  - [x] [cncf/mentoring programs](https://github.com/cncf/mentoring/tree/main/programs)

## Post term

- [x] Send thank you email to all of the mentors
- [x] Plan / setup next term (terms should be planned a year in advance - at the end of this term, plan next year's)
  - [x] 2025 Term 1 https://github.com/cncf/mentoring/pull/1307
