### ISSUE TITLE
[Umbrella] GSoC 2024 admin tasks

### ISSUE THREAD

**Issue by aliok** [cncf/mentoring#1119]
This is an umbrella task to track GSoC admin tasks for CNCF.

Last year's task:: https://github.com/cncf/mentoring/issues/859

Timeline and general information is available here: https://github.com/cncf/mentoring/discussions/1116

- [x] Announce intention to participate: https://github.com/cncf/mentoring/discussions/1116
  - Post to mailing list: https://lists.cncf.io/g/tag-cs-mentoring-wg/message/12
  - Submit to maintainers newsletter
  - Post on social media, ask CNCF to repost
  - Announce to some channels: `#ambassadors`, `#general`, `#mentoring`, ...
- [x] Organization application
- Application accepted
  - [x] Announcement: https://github.com/cncf/mentoring/discussions/1186  
  - [x] Post to mailing list: https://lists.cncf.io/g/tag-cs-mentoring-wg/message/14
  - [x] Submit to maintainers newsletter
  - [x] Post on social media, ask CNCF to repost
  - [x] Announce to some channels: `#ambassadors`, `#general`, `#mentoring`, ...
- [x] Invite mentors to GSoC platform and add them to GSoC 2024
  - [ Internal tracking sheet](https://docs.google.com/spreadsheets/d/1QjMwAWfgUv6gLKi1ldOE_YQlHAxbyanil4PJy0CiIeo/edit?usp=sharing)
- [x] Review proposals
- [x] Create mentors mailing list and add mentors to it https://github.com/cncf/mentoring/issues/1187
- [ ] Notify Google Admins of an inactive GSoC Contributors
- [x] Check project midterm reviews
- [x] Check project final reviews
- [ ] Write a blog post
- [ ] Add stats to program statistics page
