### ISSUE TITLE
[umbrella] LFX 2024 Term 2: June-August administration

### ISSUE THREAD

**Issue by aliok** [cncf/mentoring#1201]
## Before term
- [x] Plan term: already done: https://github.com/cncf/mentoring/tree/main/programs/lfx-mentorship/2024/02-Jun-Aug

## Start of term

- [x] Call for proposals announcement (about 1 month ahead of proposal due date --> March 24)
  - [x] TOC mail list - @nate-double-u to schedule an email for Apr 8, 2024 Monday @ 9:00AM PST
  - [x] Maintainers newsletter
  - [x] Discussion boards https://github.com/cncf/mentoring/discussions/1205
  - [x] Linkedin/Twitter/Mastodon
  - [x] CNCF Slack (#mentoring & #tag-contributor-strategy) https://cloud-native.slack.com/archives/CGPK98JNQ/p1712611925126959
- [x] Followup announcement about 1 week ahead of deadline (--> April 17)

## Proposals in

- [x] Load proposals into LFX platform 
  - [x] Create Jun-Aug Project, Mentor, & Mentee list (gsheet)
- [x] Open projects for application (LFX platform)
- [x] Mentee applications open announcement 
  - [x] Reach out to CNCF Socials team
  - [x] Discussion boards
  - [x] Linkedin/Twitter/Mastodon/others? Linkedin is most important based on previous traffic.
  - [x] CNCF Slack (#mentoring)
- [x] Followup email to mentors that mentees are applying (a week before deadline -- they can start looking at their candidates)
- [x] Application deadline
  - [x] Close projects for applications (LFX platform)
  - [x] email mentors that they should be making selections
- [x] Create mentor email list

## Application review/admission decisions
- [x] email mentors to make selections (share google form)
- [x] CNCF Selection admin (in LFX platform, accept project's selected mentee, decline others)
  - [x] first pass complete (most projects have been processed)
  - [x] remainder of approvals 
- [x] Create mentee email list

## Midterm

- [x] Midterm evaluation
  - [x] Create google form
  - [x] Send evaluation form to mentors (about 1-2 weeks before due) - @nate-double-u to schedule an email for July 2, 2024 @ 9:00 AM Pacific time
- [x] Send out evaluation results & stipend instructions ([Mail merge](https://developers.google.com/apps-script/samples/automations/mail-merge))
- [x] Approve stipends

## End of term

- [x] End of term evaluation (Mentors)
  - [x] Create google form
  - [x] Send evaluation form to mentors (about 1-2 weeks before due)
- [x] Send out evaluation results & stipend instructions ([Mail merge](https://developers.google.com/apps-script/samples/automations/mail-merge))
- [ ] Approve stipends
- [ ] Mentee feedback - (open form on evaluation due date, feedback/blog posts due on last day of term)
  - [ ] Send feedback form to mentees (include deadline, last day of term)
  - [ ] Send feedback reminder if needed
- [ ] Reach out to CNCF blog team to write end of term blog post (blog@cncf.io)
  - [ ] Share end of term blog post
	- [ ] Linkedin/Twitter/Mastodon
- [ ] Update statistics
  - [x] [CNCF Mentoring Stats Overview (ongoing summary)](https://docs.google.com/spreadsheets/d/13xybjxyWOHcfNn3Mmpd6zbq61gLp5Kprdsda-nJ50lM/edit?usp=sharing)
  - [ ] [cncf/mentoring Program Statistics](https://github.com/cncf/mentoring#program-statistics)
  - [ ] [cncf/mentoring programs](https://github.com/cncf/mentoring/tree/main/programs)

## Post term

- [x] Send thank you email to all of the mentors
- [ ] Plan / setup next term (terms should be planned a year in advance - at the end of this term, plan next year's)
  - [ ] 2025 Term 2
