### ISSUE TITLE
[Umbrella] GSoC 2023 admin tasks

### ISSUE THREAD

**Issue by aliok** [cncf/mentoring#859]
This is an umbrella task to track GSoC admin tasks for CNCF.

Timeline and general information is available here: https://github.com/cncf/mentoring/discussions/848

- [x] Create mentors mailing list: https://github.com/cncf/mentoring/issues/865
- [x] Invite mentors to GSoC platform and add them to GSoC 2023: Deadline is contributor application start https://github.com/cncf/mentoring/issues/864
- [x] Specify rankings and selection criteria for GSoC proposals+contributors+mentors ([discussion](https://github.com/cncf/mentoring/discussions/860) about the process), PR: https://github.com/cncf/mentoring/pull/1005
- [x] Review proposals: Hard deadline April 27 18:00 UTC
- [x] Add mentors to mailing list: https://github.com/cncf/mentoring/issues/864
- [x] Notify Google Admins of an inactive GSoC Contributors: deadline May 27
- [x] Check project midterm reviews
- [x] Check project final reviews
- [x] https://github.com/cncf/mentoring/issues/1019

**Comment by aliok** [comment]
Done!
